### ISSUE TITLE
probe / tap cause an exception if an intermediate part of the path is null

### ISSUE THREAD

**Issue by MisatoTremor** [nicholascloud/l33teral#5] opened 2016-03-07 16:09 UTC
Example:
```js
l33teral({ foo: null }).probe("foo.bar.baz");
```
will try to call hasOwnProperty on foo.

Haven't tested the other path traversing functions.

**Comment by nicholascloud** [comment] 2016-03-07 16:26
Thanks for the feedback @MisatoTremor. So, the expected behavior would be that a `GraphError` would be thrown at `bar`, then, as the `foo` segment technically exists as a property on the object, even though it is `null`. But at the present time, a generic Error is being thrown because `hasOwnProperty()` is being called on the `null` property. I will try to get a fix out shortly.

**Comment by nicholascloud** [comment] 2016-03-07 17:45
@MisatoTremor Fix has been applied, merged, and pushed to npm.

**Closed** 2016-03-07 17:46 UTC
Labels: bug

**Comment by MisatoTremor** [comment] 2016-03-08 10:42
@nicholascloud Looks good to me. Thank you very much for the super fast reply!
